# Welcome to Jekyll!
#

# Site settings
title: Friday Harbour
description: |
  New EP  
  Available soon  
  
owner: Friday Harbour # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: fridayharbourrocks@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.fridayharbour.rocks" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/fridayharbourrocks
  facebook-official: https://facebook.com/fridayharbourrocks
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  instagram: https://www.instagram.com/fridayharbourrocks/
  youtube-square: https://www.youtube.com/channel/UC3P6YegbAQ1jc8ZsRQwhpWg
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  soundcloud: https://soundcloud.com/fridayharbourrocks
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
